---
- name: "Apache installation using docker"
  hosts: prod
  become: true

  pre_tasks:
    - name: Update the packages
      apt:
        update_cache: yes 

    - name: Install some packages
      apt:
        name: '{{ item }}'
        state: present
      when: ansible_distribution == 'Ubuntu'
      loop:
        - python3
        - python3-pip
        - docker.io
 
  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/ubuntu/index.html

    - name: Create Apache container 
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/ubuntu/index.html:/usr/local/apache2/htdocs/index.html
